using System;
using System.Collections.Generic;
using Microsoft.WindowsPhone.ImageUpdate.Tools.Common;

namespace Microsoft.WindowsPhone.Multivariant.Offline
{
	// Token: 0x02000004 RID: 4
	internal class RegFileWriter
	{
		// Token: 0x17000001 RID: 1
		// (get) Token: 0x06000008 RID: 8 RVA: 0x00002304 File Offset: 0x00000504
		private static string regFileHeader
		{
			get
			{
				string text = string.Empty;
				foreach (string str in Environment.GetCommandLineArgs())
				{
					text = text + str + " ";
				}
				return string.Concat(new string[]
				{
					"; Autogenerated OEM Customizations",
					Environment.NewLine,
					"; Command Line used to generate this file:",
					Environment.NewLine,
					";    ",
					text,
					Environment.NewLine
				});
			}
		}

		// Token: 0x06000009 RID: 9 RVA: 0x0000237B File Offset: 0x0000057B
		public static void Write(List<RegValueInfo> regValueInfoList, string regFilename)
		{
			RegBuilder.BuildRegistryEntries(regValueInfoList, regFilename, true);
		}
	}
}
