using System;

namespace Microsoft.WindowsPhone.ImageUpdate.InboxAppLib
{
	// Token: 0x0200000A RID: 10
	public enum APPX_BUNDLE_PAYLOAD_PACKAGE_TYPE
	{
		// Token: 0x0400002B RID: 43
		APPX_BUNDLE_PAYLOAD_PACKAGE_TYPE_APPLICATION,
		// Token: 0x0400002C RID: 44
		APPX_BUNDLE_PAYLOAD_PACKAGE_TYPE_RESOURCE
	}
}
